name: NoAdvertisingPE
main: Vaivez66\NoAdvertisingPE\NoAdvertising
version: 1.0.1
api: [1.12.0, 2.0.0]
load: POSTWORLD
authors: [Vaivez66]
description: "Stop those advertisers!"
commands:
  na:
    description: "Manage the domain list."
    usage: "/na <add|remove|list> [domain]"
permissions:
  no.advertising.pe:
    description: "Permission to execute na"
    default: op
  no.advertising.pe.bypass:
    description: "Permission to bypass from blocking"
    default: false
