
# Available types:
#   - broadcast
#   - block
#   - kick
type: block
# The message that will be sent
# You can use {player} to mention their name
message: '{RED}Do not try to advertise!'
# Blocked domain extensions
domain:
  - ".me"
  - ".com"
  - ".net"
# Whitelisted domains
allowed.domain:
  - "yourserver.com"
  - "pocketmine.net"
# If true, content on signs will also be filtered
detect.sign: true
# Lines that will change if player advertise on sign
lines:
  - '============='
  - 'No Advertising!'
  - '============='
  - ''
# Commands that will also be filtered
blocked.cmd:
  - "/me"
  - "/tell"
